### ISSUE TITLE
Version numbers: Can we use a shortcode or something for that?

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo-docs#6]
I noticed editing the quickstart guide that there are a lot of version numbers hardcoded into the text. An that requires a somewhat tricky update process, in which one must manually search-and-replace (and which causes more trouble when two different dependencies happen to incidentally have the same version number, so global fifnd-and-replace doesn't work).

Is there a way we could write a shortcode or something that would substitute, e.g., `bindle-current-version` with `0.4.1`?

**Comment by bacongobbler** [comment]
I've started dropping shortcodes for `{{< hippo-version >}}` which can be used in the docs as a reference to the latest version of Hippo.

I didn't see a location in the docs where bindle's latest version is referenced, but if we need a shortcode for that at some point you can look at https://github.com/deislabs/hippo-docs/blob/main/layouts/shortcodes/hippo-version.html as a reference point.
